#define __QUECTEL_USER_FRIENDLY_PROJECT_VERSION "A02_BETA_20240814"


/**********************************************************
            Select quectel module
**********************************************************/
#define __QUECTEL_USER_FRIENDLY_PROJECT_MODULE_SUPPORT_BG95__
//#define __QUECTEL_USER_FRIENDLY_PROJECT_MODULE_SUPPORT_EC20__


/**********************************************************
            Select support features
**********************************************************/
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_NETWORK__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_NETWORK_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SOCKET__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SOCKET_TCP_SERVER_EXAMPLE__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SOCKET_UDP_SERVER_EXAMPLE__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SOCKET_TCP_CLIENT_EXAMPLE__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SOCKET_UDP_CLIENT_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_SSL__   /* Must  enable __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_FILESYSTEM__*/

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_HTTP_S__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_HTTP_S_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_FTP_S__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_FTP_S_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_MQTT_S__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_MQTT_S_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_TFCARD__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_FILESYSTEM__  /* Must  enable __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_TFCARD__ */
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_FILESYSTEM_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_PSM__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_PSM_EXAMPLE__

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_DEBUG_PRINT__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_DEBUG_SHELL__
#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_DEBUG_SAVE__  /* Must  enable __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_DEBUG_PRINT__  and  __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_TFCARD__*/

#define __QUECTEL_USER_FRIENDLY_PROJECT_FEATURE_SUPPORT_EXAMPLE_MAIN__

